services:
  sampledb:
    image: postgres:17.4
    environment:
      - POSTGRES_PASSWORD=password

  databasegui:
    image: dpage/pgadmin4:9.1.0
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@example.com
      - PGADMIN_DEFAULT_PASSWORD=pgadminpass
